# Generated by Django 5.2.7 on 2025-10-16 20:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = []
