# Generated by Django 5.2.7 on 2025-10-17 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_auto_20251016_2038"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="wine",
            options={
                "ordering": ["name", "vintage"],
                "verbose_name": "Wine",
                "verbose_name_plural": "Wines",
            },
        ),
        migrations.RenameField(
            model_name="wine",
            old_name="quantity_in_stock",
            new_name="qty",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="price",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="supplier",
        ),
        migrations.RemoveField(
            model_name="wine",
            name="vintage_year",
        ),
        migrations.AddField(
            model_name="wine",
            name="appellation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="bottle_size",
            field=models.PositiveIntegerField(
                blank=True, help_text="Size in cl (e.g., 75)", null=True
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wine",
            name="location",
            field=models.CharField(
                blank=True,
                help_text="Cellar or storage location",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="purchase_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="purchase_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="rating",
            field=models.CharField(
                blank=True,
                help_text="Critic or personal rating",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="region",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="status",
            field=models.CharField(
                choices=[
                    ("in_bond", "In Bond"),
                    ("in_stock", "In Stock"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                    ("consumed", "Consumed"),
                    ("other", "Other"),
                ],
                default="in_stock",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="wine",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="wine",
            name="vintage",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="wine",
            name="category",
            field=models.CharField(
                choices=[
                    ("red", "Red"),
                    ("white", "White"),
                    ("rose", "Rosé"),
                    ("champagne", "Champagne"),
                    ("rose_champagne", "Rosé Champagne"),
                    ("sparkling", "Sparkling"),
                    ("yellow", "Yellow"),
                    ("liqueur", "Liqueur"),
                    ("dessert", "Dessert"),
                    ("fortified", "Fortified"),
                    ("orange", "Orange"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="wine",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
