# Generated by Django 5.2.7 on 2025-10-27 22:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "inventory",
            "0003_alter_wine_options_rename_quantity_in_stock_wine_qty_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Wine",
            new_name="OldWine",
        ),
    ]
