# Generated by Django 5.2.7 on 2025-10-27 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_rename_wine_oldwine"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("vintage", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("red", "Red"),
                            ("white", "White"),
                            ("rose", "Rosé"),
                            ("champagne", "Champagne"),
                            ("rose_champagne", "Rosé Champagne"),
                            ("sparkling", "Sparkling"),
                            ("yellow", "Yellow"),
                            ("liqueur", "Liqueur"),
                            ("dessert", "Dessert"),
                            ("fortified", "Fortified"),
                            ("orange", "Orange"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                ("region", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "appellation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "rating",
                    models.CharField(
                        blank=True,
                        help_text="Critic or personal rating",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name", "vintage"],
            },
        ),
        migrations.CreateModel(
            name="WineInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bottle_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="Size in cl (e.g., 75)", null=True
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=0)),
                (
                    "purchase_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=255, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_bond", "In Bond"),
                            ("in_stock", "In Stock"),
                            ("reserved", "Reserved"),
                            ("sold", "Sold"),
                            ("consumed", "Consumed"),
                            ("other", "Other"),
                        ],
                        default="in_stock",
                        max_length=50,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="Cellar or storage location",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inventories",
                        to="inventory.wine",
                    ),
                ),
            ],
        ),
    ]
