# Generated by Django 5.2.7 on 2025-10-27 23:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_wine_wineinventory"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OldWine",
        ),
    ]
