# Generated by Django 5.2.7 on 2025-11-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_winelist_wineitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wineinventory",
            name="status",
            field=models.CharField(
                choices=[
                    ("proposed", "Proposed"),
                    ("in_bond", "In Bond"),
                    ("in_stock", "In Stock"),
                    ("reserved", "Reserved"),
                    ("sold", "Sold"),
                    ("consumed", "Consumed"),
                    ("other", "Other"),
                ],
                default="in_stock",
                max_length=50,
            ),
        ),
    ]
